### ISSUE TITLE
FR: Current language on top

### ISSUE THREAD

**Issue by neckarpixel** [terminal42/contao-changelanguage#108]
Hello to terminal42,
it would be great to be able to sort the current language to the first element in the language array.
Example:
DE (Current), EN, FR -> change to english
EN (Current), DE, FR

Thx.

**Comment by aschempp** [comment]
You can achieve that by adding the custom language texts and sorting them in the order you need them…

**Comment by Toflar** [comment]
I guess the desired feature is to always show the active page at first position. I don't know why this should ever make sense but well... :)

**Comment by aschempp** [comment]
Yeah that's my point… I don't really see a generic need for that, and it can already be achieved either by the config or by template hacking. That should be enough for the rare cases…?

**Comment by dhe** [comment]
Puh, ok. I'll try to explain my thoughts.
I need the current language in the first element of the nav list

Step1: Current Language EN
<img width="558" alt="step1" src="https://cloud.githubusercontent.com/assets/130322/23498084/460cb97c-ff26-11e6-83a7-3ea3c811d1f5.png">

Step2: Hover on ul to show all available languages (DE,FR) and change to DE
<img width="543" alt="step2" src="https://cloud.githubusercontent.com/assets/130322/23498226/de14e06e-ff26-11e6-986d-7a2b7c20bf59.png">

Step3: Landing on DE Page, Language Select shows "EN" instead of "DE" on first position in ul
<img width="539" alt="step3" src="https://cloud.githubusercontent.com/assets/130322/23498274/381f5968-ff27-11e6-8bfc-af945eea4a78.png">

Step4: Hover on ul
<img width="546" alt="step4" src="https://cloud.githubusercontent.com/assets/130322/23498298/69192f76-ff27-11e6-83fd-dd784d7fda6c.png">

At this position i think the correct order should be DE,EN,FR

At the moment i'm using an own nav_language.html5 template where i'm manipulating the order.
```php
<?php $arrLangNav = []; ?>
<ul class="<?= $this->level ?>">
	<?php foreach ($this->items as $navElement):
		if ($navElement['isActive']):
			array_unshift($arrLangNav, $navElement);
		else:
			$arrLangNav[] = $navElement;
		endif;
	endforeach; ?>
   <?php foreach ($arrLangNav as $item): ?>
    <?php if ($item['isActive']): ?>
      <li class="<?= $item['class'] ?>"><span class="<?= $item['class'] ?>"<?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?>><?= $item['link'] ?></span><?= $item['subitems'] ?></li>
    <?php else: ?>
      <li<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?>><a href="<?= $item['href'] ?: './' ?>" title="<?= $item['pageTitle'] ?: $item['title'] ?>"<?php if ($item['class']) echo ' class="' . $item['class'] . '"'; ?><?php if ($item['accesskey']) echo ' accesskey="' . $item['accesskey'] . '"'; ?><?php if ($item['tabindex']) echo ' tabindex="' . $item['tabindex'] . '"'; ?><?php if ($item['nofollow']) echo ' rel="nofollow"'; ?><?= $item['target'] ?><?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?>><?= $item['link'] ?></a><?= $item['subitems'] ?></li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>
```

**Comment by fritzmg** [comment]
You don't really have to manipulate the order, you can just output the current language separately and then not show the current language in the loop.

**Comment by dhe** [comment]
Hm, also a good idea but that won't work when i want to use custom language texts...

**Comment by fritzmg** [comment]
Yes, but there are custom solutions for that as well ;).

Just to add my 2 cents: I had at least two or three instances where I had to do something similar on a website. The principle was the same as @dhe explained: a language menu where only the active language is displayed and on hover the other language choices are selectable. So far I didn't mind having to create a custom template for that though.

**Comment by Toflar** [comment]
I mean, I don't really care. Adding this feature is just a new checkbox in the front end module settings and 2, 3 lines of code in the front end module. Shouldn't be a big deal. So we might as well just add it in a future version.
