### ISSUE TITLE
Is it possible to have a reference page other than root and still switch languages?

### ISSUE THREAD

**Issue by x-christian-romeni** [terminal42/contao-changelanguage#148]
Ok, so I have a regular navigation but I'm changing the reference page to a Folder.
Let say my Page structure is:

- DE Home
-- DE Branchen (Folder) / selected in the navigation module
--- Lebensmittel
--- Süßwaren
--- Getränke

- EN Home
-- EN Branchen (Folder)
--- Food
--- Sweets
--- Baverages

![image](https://user-images.githubusercontent.com/30910746/39620511-b4c8f9e6-4f8b-11e8-91d6-4c5a5bd01dda.png)

![image](https://user-images.githubusercontent.com/30910746/39620622-10346234-4f8c-11e8-8636-e023ace3011d.png)

Is it possible, when switching to english, that the same navigation module can be used and uses the defined english reference page automatically?

**Comment by fritzmg** [comment]
This would need to be a custom navigation module that automatically switches the reference page based on the current language. Should be pretty simple: you just need to extend the existing `Contao\ModuleNavigation` module, override the `compile()` method and set the `$this->rootPage` variable according to the current language - and then simply call `parent::compile()`.

**Comment by aschempp** [comment]
This is not related to changelanguage, please refer to the community forums.

**Comment by fritzmg** [comment]
It is related to changelanguage :). I'll may be make a PR for such a feature. Though it might be out of scope for the changelanguage extension and thus better suited in its own independent extension.

**Comment by aschempp** [comment]
It is not related. Changelanguage has one purpose: render a menu/selector to switch the language. The issue is related to multilingual websites, but that's not changelanguage 😉 

Btw. you might want to check out https://github.com/terminal42/contao-rootcontent as it allows for kind-of multilingual front end modules 😎

**Comment by fritzmg** [comment]
> It is not related. Changelanguage has one purpose: render a menu/selector to switch the language. The issue is related to multilingual websites, but that's not changelanguage 😉

Imho the primary purpose of changelanguage is the ability to set a reference page in the main language. Having a module that allows you to switch between languages is a bonus, since it does not offer a lot more functionality, if you did _not_ define reference pages.

These references can then also be used to automatically _change_ (😉) the reference in modules that define pages or reference pages, like the navigation, custom navigation or search module for instance. This way you only have to create one of each these modules, instead of one for each module and language.
